<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <!-- <TargetFrameworks>net48</TargetFrameworks> -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <PackageId>ModelContextProtocol.Core</PackageId>
    <Description>Core .NET SDK for the Model Context Protocol (MCP)</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Common\Throw.cs" Link="Throw.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\Polyfills\**\*.cs" />
    <PackageReference Include="Microsoft.Bcl.Memory" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Threading.Channels" />
    <!-- <PackageReference Include="System.Net.ServerSentEvents" /> -->
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Memory" />

  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
